version: '3.3'
services:
  neo4j:
    image: neo4j:3.5.5
    volumes:
      - ./conf:/var/lib/neo4j/conf
      - ./mnt:/var/lib/neo4j/import
      - ./plugins:/plugins
      - ./data:/data
      - ./logs:/var/lib/neo4j/logs
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_heap_maxSize=1G
      - NEO4J_AUTH=neo4j/11111111  #修改默认用户密码
