version: '3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    restart: always
    container_name: xxl-job-admin
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://106.14.148.37:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=11111111'
    ports:
      - 8090:8080 # 主机的8090端口 映射容器的8080端口
    volumes:
      - ./data/applogs:/data/applogs
