version: "3"
services:
  sonar:
    image: sonarqube:7.9-community
    restart: always 
    container_name: sonarqube
    depends_on:
      - postgres
    volumes:
      - /dockerdata/sonarqube/extensions:/opt/sonarqube/extensions
      - /dockerdata/sonarqube/logs:/opt/sonarqube/logs
      - /dockerdata/sonarqube/data:/opt/sonarqube/data
      - /dockerdata/sonarqube/conf:/opt/sonarqube/conf
    ports:
      - 9010:9000
    environment:
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: yang$$1111
      SONARQUBE_JDBC_URL: jdbc:postgresql://106.14.148.37:5432/sonar