version: '3.7'
networks:
  swarm-net:
    external:
      name: swarm-net
services:
  zookeeper-server-a:
    container_name: zookeeper-server-a   # https://github.com/31z4/zookeeper-docker/tree/master/3.5.6
    image: zookeeper:3.6.1
    hostname: zookeeper-server-a
    ports:
     - target: 2181
       published: 12181
       protocol: tcp
       mode: host
    networks:
     - swarm-net
    environment:
      ZOO_MY_ID: "1"
      ZOO_SERVERS: "server.1=0.0.0.0:2888:3888;2181 server.2=8.141.54.77:2888:3888;2181 server.3=112.125.27.229:2888:3888;2181"
      ZOO_DATA_DIR: "/data/"
    volumes:
      - /opt/zk/1/:/data
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [node.hostname == yang]
      resources:
        limits:
          memory: 1024M
  zookeeper-server-b:
    container_name: zookeeper-server-b
    image: zookeeper:3.6.1
    hostname: zookeeper-server-b
    ports:
     - target: 2181
       published: 22181
       protocol: tcp
       mode: host
    networks:
     - swarm-net
    environment:
      ZOO_MY_ID: "2"
      ZOO_SERVERS: "server.1=106.14.148.37:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=112.125.27.229:2888:3888;2181"
      ZOO_DATA_DIR: "/data/"
    volumes:
      - /opt/zk/2/:/data
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [node.hostname == yang-bj-1]
      resources:
        limits:
          memory: 1024M
  zookeeper-server-c:
    container_name: zookeeper-server-c
    image: zookeeper:3.6.1
    hostname: zookeeper-server-c
    ports:
     - target: 2181
       published: 32181
       protocol: tcp
       mode: host
    networks:
     - swarm-net
    environment:
      ZOO_MY_ID: "3"
      ZOO_SERVERS: "server.1=106.14.148.37:2888:3888;2181 server.2=8.141.54.77:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181"
      ZOO_DATA_DIR: "/data/"
    volumes:
      - /opt/zk/3/:/data
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [node.hostname == yang-bj-2]
      resources:
        limits:
          memory: 1024M