version: '3.7'
services:
  zookeeper-server-a:
    container_name: zookeeper-server-a   # https://github.com/31z4/zookeeper-docker/tree/master/3.5.6
    image: zookeeper:3.6.1
    hostname: zookeeper-server-a
    ports:
     - 12181:2181
    networks:
     - swarm-net
    environment:
      ZOO_MY_ID: "1"
      ZOO_SERVERS: "server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper-server-b:2888:3888;2181 server.3=zookeeper-server-c:2888:3888;2181"
      ZOO_DATA_DIR: "/data/"
    volumes:
      - /opt/zk/1/:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == yang]
      resources:
        limits:
          memory: 1024M
  zookeeper-server-b:
    container_name: zookeeper-server-b
    image: zookeeper:3.6.1
    hostname: zookeeper-server-b
    ports:
     - 22181:2181
    networks:
     - swarm-net
    environment:
      ZOO_MY_ID: "2"
      ZOO_SERVERS: "server.1=zookeeper-server-a:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper-server-c:2888:3888;2181"
      ZOO_DATA_DIR: "/data/"
    volumes:
      - /opt/zk/2/:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == yang-bj-1]
      resources:
        limits:
          memory: 1024M
  zookeeper-server-c:
    container_name: zookeeper-server-c
    image: zookeeper:3.6.1
    hostname: zookeeper-server-c
    ports:
     - 32181:2181
    networks:
     - swarm-net
    environment:
      ZOO_MY_ID: "3"
      ZOO_SERVERS: "server.1=zookeeper-server-a:2888:3888;2181 server.2=zookeeper-server-b:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181"
      ZOO_DATA_DIR: "/data/"
    volumes:
      - /opt/zk/3/:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == yang-bj-3]
      resources:
        limits:
          memory: 1024M