version: "3.2"
services:
#kafka manager服务
  kafka-manager:
    hostname: kafka-manager
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - "19000:9000"
    networks:
      swarm-net:
        aliases:
          - kafka-manager
    environment:
      - ZK_HOSTS=zookeeper-server-a:2181,zookeeper-server-b:2181,zookeeper-server-c:2181
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == yang]
      resources:
        limits:
#          cpus: '1'
          memory: 1GB
        reservations:
#          cpus: '0.2'
          memory: 512M

networks:
  avatar-net:
    external:
      name: swarm-net