version: '3.7'
networks:
  swarm-net:
services:
  zookeeper-server-a:
    image: zookeeper:3.4
    hostname: zookeeper-server-a
    networks:
      - swarm-net
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper-server-b:2888:3888;2181 server.3=zookeeper-server-c:2888:3888;2181
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.hostname == yang
      restart_policy:
        condition: any

  zookeeper-server-b:
    image: zookeeper:3.4
    hostname: zookeeper-server-b
    ports:
      - 2181:2181
    networks:
      - swarm-net
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-server-a:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper-server-c:2888:3888;2181
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.hostname == yang-bj-1
      restart_policy:
        condition: any

  zookeeper-server-c:
    image: zookeeper:3.4
    hostname: zookeeper-server-c
    ports:
      - 2181:2181
    networks:
      - swarm-net
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-server-a:2888:3888;2181 server.2=zookeeper-server-b:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.hostname == yang-bj-2
      restart_policy:
        condition: any
