version: "3.3"
services:
    zookeeper:
        image: zookeeper
        ports:
          - 2181:2181
          - 2888:2888
          - 3888:3888
        networks:
          - esnet1
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
    nimbus:
        image: storm
        command: storm nimbus
        hostname: 112.125.27.229
        volumes:
            - logs:/logs
        depends_on:
            - zookeeper
        networks:
          - esnet1
        ports:
            - 6627:6627
        deploy:
            restart_policy:
                condition: on-failure
    supervisor:
        image: storm
        command: storm supervisor -c storm.log.dir="/logs"
        hostname: 112.125.27.229
        depends_on:
            - nimbus
            - zookeeper
        networks:
          - esnet1
#        volumes:
#          - type: bind
#            source: /data/storm
#            target: /data
#          - type: volume
#            source: logs
#            target: /logs
        deploy:
            #mode: global
            replicas: 1
            placement:
                constraints:
                  - node.labels.processor==true
            restart_policy:
                condition: on-failure
    ui:
        image: storm
        command: storm ui -c storm.log.dir="/logs"
        volumes:
            - logs:/log
        networks:
          - esnet1
        depends_on:
            - nimbus
        ports:
            - 8071:8080
        deploy:
            restart_policy:
                condition: on-failure
networks:
  esnet1:
    attachable: true
volumes:
    logs: