version: '3.7'

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      - PRE_CREATE_DB=prometheus
      - ADMIN_USER="admin"
      - INFLUXDB_INIT_PWD="admin111111"
      - GOGC=10
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
    ports:
      - "8086:8086"
    volumes:
      - "/usr/share/influxdb:/var/lib/influxdb"