version: '3.7'

services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          memory: 2048m
        reservations:
          memory: 200m
    volumes:
      - "/usr/share/influxdb:/var/lib/influxdb"